### ISSUE TITLE
Pressing delete at the first column might lead to the ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kamil-sita** [e3ndr/Atto#1]
**To reproduce:**

1. Write some string, for example "hello world"
2. Move cursor to the first column
3. Press "delete" key twice

**alternatively:**

1. Write some string, for example "hello world"
2. Move cursor to the first column
3. Press "delete" key
4. Try to type anything

**Results:**

> Exception in thread "ConsoleUtil - Key Listener Thread" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 11
>         at xyz.e3ndr.atto.util.CharMap.set(CharMap.java:42)
>         at xyz.e3ndr.atto.ui.TextEditorScreen.onKey(TextEditorScreen.java:302)
>         at xyz.e3ndr.consoleutil.input.KeyHook.broadcast(KeyHook.java:139)
>         at xyz.e3ndr.consoleutil.input.KeyHook.read(KeyHook.java:92)
>         at xyz.e3ndr.consoleutil.input.KeyHook.access$100(KeyHook.java:14)
>         at xyz.e3ndr.consoleutil.input.KeyHook$1.run(KeyHook.java:43)

**Probable cause:** 

after pressing "delete" the cursor moves to the previous position, ignoring any bounds. If you press "delete" in the first column, it goes to -1. Next array access will use -1 as its position, leading to the exception.

**Comment by e3ndr** [comment]
~~What version does this affect?~~

Edit: Re-read title, working on it now.

**Comment by e3ndr** [comment]
Fixed in release [2.1.2](https://github.com/e3ndr/Atto/releases/tag/2.1.2).
